name: gtk-maxes-themes
adopt-info: version-script
architectures:
  - build-on: amd64
    run-on: all
summary: Max's custom GTK themes and icons
description: |
  A snap that exports Max's custom GTK themes and icons.

# We build against Ubuntu 20.04 packages, but use the "bare" base as
# we don't want to force installation of a large base snap.
build-base: core20
base: bare
compression: lzo

grade: stable
confinement: strict

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Fluent-round-teal
        - $SNAP/share/themes/Fluent-round-teal-compact
        - $SNAP/share/themes/Fluent-round-teal-Dark 
        - $SNAP/share/themes/Fluent-round-teal-Dark-compact 
        - $SNAP/share/themes/Fluent-round-teal-Light
        - $SNAP/share/themes/Fluent-round-teal-Light-compact
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Fluent-round-teal
        - $SNAP/share/themes/Fluent-round-teal-compact
        - $SNAP/share/themes/Fluent-round-teal-Dark 
        - $SNAP/share/themes/Fluent-round-teal-Dark-compact 
        - $SNAP/share/themes/Fluent-round-teal-Light
        - $SNAP/share/themes/Fluent-round-teal-Light-compact
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Yaru
        - $SNAP/share/icons/Yaru-bark
        - $SNAP/share/icons/Yaru-blue
        - $SNAP/share/icons/Yaru-magenta
        - $SNAP/share/icons/Yaru-olive
        - $SNAP/share/icons/Yaru-prussiangreen
        - $SNAP/share/icons/Yaru-purple
        - $SNAP/share/icons/Yaru-red
        - $SNAP/share/icons/Yaru-sage
        - $SNAP/share/icons/Yaru-viridian
        - $SNAP/share/icons/Yaru-dark
        - $SNAP/share/icons/Yaru-bark-dark
        - $SNAP/share/icons/Yaru-blue-dark
        - $SNAP/share/icons/Yaru-magenta-dark
        - $SNAP/share/icons/Yaru-olive-dark
        - $SNAP/share/icons/Yaru-prussiangreen-dark
        - $SNAP/share/icons/Yaru-purple-dark
        - $SNAP/share/icons/Yaru-red-dark
        - $SNAP/share/icons/Yaru-sage-dark
        - $SNAP/share/icons/Yaru-viridian-dark
  sound-themes:
    interface: content
    source:
      read:
        - $SNAP/share/sounds/Yaru

parts:
  version-script:
    plugin: nil
    source: .
    build-packages:
      - git
    override-build: |
      snapcraftctl set-version $(git -C $SNAPCRAFT_PROJECT_DIR describe --tags 2>/dev/null || echo 0.1)

  # Yaru, the new official Ubuntu theme in 18.10 (formerly known by its code name Communitheme)
  yaru:
    after: [utils]
    source: https://github.com/ubuntu/yaru.git
    source-depth: 1
    #source-tag: 22.04.3.1
    source-commit: 8afd77f61a07813f97c941a3a7e5c0a51f6420da
    #source-branch: ubuntu/impish
    plugin: meson
    meson-parameters:
      - --prefix=/
      - -Dgnome-shell=false
      - -Dsessions=false
      - -Dmate=true
      - -Dmate-dark=true
    build-packages:
      - sassc
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
      $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
      # Link Yaru to Yaru-light to support < Jammy
      themes_path=$SNAPCRAFT_PART_INSTALL/share/themes
      mkdir -p $themes_path/Yaru-light
      cp $themes_path/Yaru/index.theme \
        $themes_path/Yaru-light/
      sed -i 's,^Name=Yaru$,Name=Yaru-light,g' \
        $themes_path/Yaru-light/index.theme
      for t in $themes_path/Yaru/*; do
        target=$(basename $t)
        if [ ! -e $themes_path/Yaru-light/$target ]; then
          ln -sv ../Yaru/$target $themes_path/Yaru-light/
        fi
      done
      # Link Yaru-mate to Yaru-MATE to support < 22.10
      gtk2_path=$SNAPCRAFT_PART_INSTALL/share/gtk2
      ln -sv Yaru-mate $gtk2_path/Yaru-MATE-light
      ln -sv Yaru-mate-dark $gtk2_path/Yaru-MATE-dark

      mkdir -p $themes_path/Yaru-MATE-light
      cp $themes_path/Yaru-mate/index.theme \
        $themes_path/Yaru-MATE-light/
      sed -i 's,^Name=Yaru-mate$,Name=Yaru-MATE-light,g' \
        $themes_path/Yaru-MATE-light/index.theme
      sed -i 's,^GtkTheme=Yaru-mate$,GtkTheme=Yaru-MATE-light,g' \
        $themes_path/Yaru-MATE-light/index.theme
      sed -i 's,^IconTheme=Yaru-mate$,IconTheme=Yaru-MATE-light,g' \
        $themes_path/Yaru-MATE-light/index.theme
      for t in $themes_path/Yaru-mate/*; do
        target=$(basename $t)
        if [ ! -e $themes_path/Yaru-MATE-light/$target ]; then
          ln -sv ../Yaru-mate/$target $themes_path/Yaru-MATE-light/
        fi
      done

      mkdir -p $themes_path/Yaru-MATE-dark
      cp $themes_path/Yaru-mate-dark/index.theme \
        $themes_path/Yaru-MATE-dark/
      sed -i 's,^Name=Yaru-mate-dark$,Name=Yaru-MATE-dark,g' \
        $themes_path/Yaru-MATE-dark/index.theme
      sed -i 's,^GtkTheme=Yaru-mate-dark$,GtkTheme=Yaru-MATE-dark,g' \
        $themes_path/Yaru-MATE-dark/index.theme
      sed -i 's,^IconTheme=Yaru-mate-dark$,IconTheme=Yaru-MATE-dark,g' \
        $themes_path/Yaru-MATE-dark/index.theme
      for t in $themes_path/Yaru-mate-dark/*; do
        target=$(basename $t)
        if [ ! -e $themes_path/Yaru-MATE-dark/$target ]; then
          ln -sv ../Yaru-mate-dark/$target $themes_path/Yaru-MATE-dark/
        fi
      done

      icons_path=$SNAPCRAFT_PART_INSTALL/share/icons
      mkdir -p $icons_path/Yaru-MATE-light
      cp $icons_path/Yaru-mate/index.theme \
        $icons_path/Yaru-MATE-light/
      sed -i 's,^Name=Yaru-mate$,Name=Yaru-MATE-light,g' \
        $icons_path/Yaru-MATE-light/index.theme
      for t in $icons_path/Yaru-mate/*; do
        target=$(basename $t)
        if [ ! -e $icons_path/Yaru-MATE-light/$target ]; then
          ln -sv ../Yaru-mate/$target $icons_path/Yaru-MATE-light/
        fi
      done

      mkdir -p $icons_path/Yaru-MATE-dark
      cp $icons_path/Yaru-mate-dark/index.theme \
        $icons_path/Yaru-MATE-dark/
      sed -i 's,^Name=Yaru-mate-dark$,Name=Yaru-MATE-dark,g' \
        $icons_path/Yaru-MATE-dark/index.theme
      for t in $icons_path/Yaru-mate-dark/*; do
        target=$(basename $t)
        if [ ! -e $icons_path/Yaru-MATE-dark/$target ]; then
          ln -sv ../Yaru-mate-dark/$target $icons_path/Yaru-MATE-dark/
        fi
      done

    stage:
      - share/icons
      - share/sounds
      - share/gtk2
      - share/themes

  # Fluent-round-teal - additional theme
  fluent-round-teal:
    after: [utils]
    plugin: nil
    source: https://github.com/vinceliuice/Fluent-gtk-theme.git
    source-tag: "2023-06-20"
    override-build: |
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
        ./install.sh -t teal -i ubuntu --tweaks solid float round square --dest $SNAPCRAFT_PART_INSTALL/share/themes
        $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*

  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
